# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
array_uni = np.array([1,2,3,4,5])

# O un array de dos dimensiones (bidimensional)
array_bidi = np.array([[1,2,3],
                       [4,5,6]])
# O un array de tres dimensiones (tridimensional)
array_tridi = np.array([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]]])

Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_uni.shape, array_uni.ndim, array_uni.dtype, array_uni.size, type(array_uni)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Atributos del array bidimensional
array_bidi.shape, array_bidi.ndim, array_bidi.dtype, array_bidi.size, type(array_bidi)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Atributos del array tridimensional
array_tridi.shape, array_tridi.ndim, array_tridi.dtype, array_tridi.size, type(array_tridi)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd
datos = pd.DataFrame(array_bidi)
datos

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
cero = np.zeros((2, 4, 3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 100, 5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[5, 2, 3, 2, 8],
       [3, 5, 4, 3, 0]])

In [ ]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3, 5))
array_3

array([[0.88328982, 0.87216568, 0.13412573, 0.2522925 , 0.17288461],
       [0.81060708, 0.89630005, 0.92262159, 0.98638662, 0.4531978 ],
       [0.25155521, 0.3302864 , 0.9760232 , 0.42200192, 0.47383787]])

In [ ]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, (3, 5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [19]:
# Encontramos los valores únicos del array_4
np.unique(array_4)


array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [20]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [22]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [23]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [25]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array5 = np.random.randint(0, 10, (3, 4))
array6 = np.ones((3, 4))

In [26]:
# invocamos el array_5
array5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [27]:
# invocamos el array_6
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# Sumamos los dos arrays
array5 + array6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [29]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array7 = np.ones((4, 3))
array7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# Intentaremos sumar los arrays 6 y 7
array6 + array7

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [31]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array8 = np.ones((4, 3))
array8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# Restamos el array_8 al array_7
array8 - array7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array9 = np.random.randint(1, 5, (3, 3))
array10 = np.random.randint(1, 5, (3, 3))


array([[1, 4, 1],
       [2, 4, 2],
       [3, 3, 1]])

In [35]:
# invocamos el array_9
array9


array([[4, 1, 1],
       [1, 2, 2],
       [1, 1, 4]])

In [36]:
# invocamos el array_10
array10

array([[1, 4, 1],
       [2, 4, 2],
       [3, 3, 1]])

In [37]:
# Multiplicamos los últimos dos arrays entre sí
array9 * array10

array([[4, 4, 1],
       [2, 8, 4],
       [3, 3, 4]])

In [38]:
# Elevamos el array_9 al cuadrado
array9**2

array([[16,  1,  1],
       [ 1,  4,  4],
       [ 1,  1, 16]])

In [39]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array10)

array([[1.        , 2.        , 1.        ],
       [1.41421356, 2.        , 1.41421356],
       [1.73205081, 1.73205081, 1.        ]])

In [40]:
# Hallamos el promedio de los valores del array_9
array9.mean()

1.8888888888888888

In [41]:
# Hallamos el valor máximo de los valores del array_9
array9.max()

4

In [42]:
# Hallamos el valor mínimo de los valores del array_9
array9.min()

1

In [43]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array11 = array9.reshape(9, 1)

In [44]:
# invocamos el array_11
array11

array([[4],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [4]])

In [46]:
# Transponemos el array_11
array11.T

array([[4, 1, 1, 1, 2, 2, 1, 1, 4]])

In [48]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array12 = array9 > array10
array12

array([[ True, False, False],
       [False, False, False],
       [False, False,  True]])

¿Qué tipos de datos forman parte del array de resultados?

In [49]:
# Veamos sus nuevos tipos de datos
array12.dtype

dtype('bool')

In [51]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array9 == array10

array([[False, False,  True],
       [False, False,  True],
       [False, False, False]])

In [52]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array9 >= array10

array([[ True, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [53]:
# Buscamos los elementos del array_9 que son mayores a 2
array9 > 2

array([[ True, False, False],
       [False, False, False],
       [False, False,  True]])

In [56]:
# Ordenamos de menor a mayor los elementos dentro del array_9
array9.sort()
array9

array([[1, 1, 4],
       [1, 2, 2],
       [1, 1, 4]])